package Objects;

import org.openqa.selenium.By;

public class Locators {

    public static By user_name = By.xpath("//input[@placeholder='Username']");
    public static By password = By.xpath("//input[@placeholder='Password']");
    public static By login_button = By.xpath("//button[text()='Login']");
    public static By home_button = By.xpath("//div[text()='Home']");
    public static By profile = By.xpath("(//*[local-name()='svg' and @data-icon=\"arrow-right-from-bracket\"]/*[local-name()='path'])");
    public static By log_out = By.xpath("//span[text()='Logout']");
    public static By page_title = By.xpath("//div[text()='Jewel Applications']");
    public static By autolytics = By.xpath("(//div[text()='Autolytics'])[2]");
    public static By bridge_token = By.xpath("(//div[text()='Bridge Token'])[2]");
    public static By copy_bridge_token = By.xpath("//div[@class='copyIcon col-2 d-flex justify-content-center align-items-center']");
    public static By copy_alert = By.xpath("//div[text()='Copied !']");
    public static By change_token = By.xpath("//div[text()='Change Token']");
    public static By date_tab = By.xpath("//div[@class='createdOn mt-3']");
    public static By change_token_alert = By.xpath("//div[text()='Bridge Token Changed Successfully.']");
    public static By pelement = By.xpath("//div[@class='d-flex']");
    public static By lelement = By.xpath("//div[@class='dropdown-item mx-auto text-center']");
    public static By cards = By.xpath("//div[@class='card-body ms-2']");
    public static By card_one = By.xpath("(//div[@class='mt-3 cardName'])[1]");
    public static By content_card_one = By.xpath("(//div[@class='mt-1 appCardContent'])[1]");
    public static By card_two = By.xpath("(//div[@class='mt-3 cardName'])[2]");
    public static By content_card_two = By.xpath("(//div[@class='mt-1 appCardContent'])[2]");
    public static By login_alert = By.xpath("//div[@role='alert']");
    public static By three_lines_button = By.xpath("(//*[local-name()='svg' and @data-icon=\"circle-chevron-left\"]/*[local-name()='path'])");
    public static By signup_button = By.xpath("//span[text()='Sign up']");
    public static By first_name = By.xpath("//input[@placeholder='Firstname']");
    public static By last_name = By.xpath(" //input[@placeholder='Lastname']");
    public static By email = By.xpath("//input[@placeholder='Email']");
    public static By confirm_pass = By.xpath("//input[@placeholder='Confirm Password']");
    public static By company_name = By.xpath("//input[@placeholder='Company Name']");
    public static By register_button = By.xpath("//button[text()='Register']");
    public static By register_alert = By.xpath("//div[text()='User Registered.']");
    public static By create_report = By.xpath("//span[text()='Create Report']");
    public static By report_name_button = By.xpath("//span[text()='Select Report Name']");
    public static By suite_run = By.xpath("//li[text()='Suite Run Report']");
    public static By project_name = By.xpath("//div[text()='Select Project Name(s)']");
    public static By project_name_selection = By.xpath("//span[text()='JEWEL-UI-JV']");
    public static By cross_button = By.xpath("//button[@class='p-multiselect-close p-link']");
    public static By env_tab = By.xpath("//div[text()='Select Environment(s)']");
    public static By select_env = By.xpath("(//div[@class=\"p-checkbox-box\"])[1]");
    public static By cbutton = By.xpath("//span[@class='p-multiselect-close-icon pi pi-times']");
    public static By date_range_tab = By.xpath("//span[text()='Select Date Range']");
    public static By select_date = By.xpath("//li[text()='This Year']");
    public static By generate_button = By.xpath("//button[text()='GENERATE']");
    public static By new_tab = By.xpath("//i[@class='pi pi-plus-circle']");
    public static By left_tabs = By.xpath("//div[@class='tabPane  align-items-center nav nav-pills']/div[starts-with(@id,'left-tabs')]");
    public static By left_most_tab = By.xpath("//button[@id='slideLeftLeft']");
    public static By right_most_tab = By.xpath("//button[@id='slideRightRight']");
    public static By slide_left = By.xpath("//button[@id='slideLeft']");
    public static By slide_right = By.xpath("//button[@id='slideRight']");
    public static By copy_report_link = By.xpath("//label[@title='Copy Report Link']");
    public static By check_text_of_report = By.xpath("//div[@class='me-3 content d-flex align-items-center']");
    public static By tabs = By.xpath("(//div[starts-with(@id,'left-tabs-example-tabParent')])[4]/a");
    public static By parent_tab = By.xpath("(//div[starts-with(@id,'left-tabs-example-tabParent')])[3]/a");
    public static By tab_select = By.xpath("(//div[starts-with(@id,'left-tabs-example-tabParent')])[1]/a");
    public static By right_most = By.xpath("(//div[starts-with(@id,'left-tabs-example-tabParent')])[5]/a");

    public static By left_next = By.xpath("(//div[starts-with(@id,'left-tabs-example-tabParent')])[4]/a");


    public static By logIn = By.xpath("//*[@class='btn-text-login fw-normal']");
    public static By searchBox = By.xpath("//*[@title='Search']");
    public static By jewel = By.xpath("//*[@class='LC20lb MBeuO DKV0Md']");
    public static By username = By.xpath("//*[@class='form-control']");
    public static By passwordm = By.xpath("//*[@type='password']");
    public static By register_newww = By.xpath("//span[text()=\"Register New User\"]");
    public static By close = By.xpath("//*[@class='crossicon']");
    public static By LoginButton = By.xpath("//*[@type='submit']");
    public static By pricing = By.xpath("//*[@href='#/pricing']");
    public static By pricingheading = By.xpath("//*[@class='headingtext']");
    public static By eye = By.xpath("//*[@class=\"pi pi-eye\"]");
    public static By eyeclose = By.xpath("//*[@class=\"pi pi-eye-slash\"]");
    public static By pricingsubheading = By.xpath("//*[@class='headingsubtext']");
    public static By jewelheading = By.xpath("//*[@class='mainHead mt-5 ms-5']");
    public static By jewelsubheading = By.xpath("//*[@class='subHead ms-5']");
    // public static By jewelink = By.xpath("//*[@src='/static/media/logo.67ff04482762962f73e1e6ad28de5771.svg']");
    public static By whatisjewel = By.xpath("//*[@class='headtext']");
    public static By aboutus = By.xpath("//*[@class='under']");
    public static By content = By.xpath("//*[@class='underText text-center px-5 my-5 ']");
    public static By viewreport = By.xpath("//*[text()='View Report']");
    public static By viewreportcontent = By.xpath("//*[@class='whatisData mb-5 px-3']");
    public static By pricingcontent = By.xpath("//*[@class='paraText']");
    public static By jewelconetnt = By.xpath("//*[@class='subHead ms-5']");
    public static By runtest = By.xpath("//*[text()='Run Test Suite']");
    public static By runtestc = By.xpath("(//*[@class='whatisData mb-5 px-3'])[2]");
    public static By facebook = By.xpath("(//*[@class='icon_links'])[1]");
    public static By twitter = By.xpath("(//*[@class='icon_links'])[2]");
    public static By instagram = By.xpath("(//*[@class='icon_links'])[3]");
    public static By linkedin = By.xpath("(//*[@class='icon_links'])[4]");
    public static By jeweldashboard = By.xpath("//*[text()='Jewel dashboard']");
    public static By gempyp = By.xpath("//*[text()=' GemPYP']");
    public static By gemprf = By.xpath("//*[text()='GemPRF']");
    public static By gemjar = By.xpath("//*[text()='GemJAR']");
    public static By pricingbutton = By.xpath("//*[text()='Pricing ']");
    public static By autolyticsm = By.xpath("//*[text()='Autolytics']");
    public static By createReport = By.xpath("//*[@class='emptyText py-2 px-3 btn btn-sm ']");
    public static By checkboxxx = By.xpath("(//div[@class=\"p-checkbox-box\"])[1]");
    public static By reporting_new_btn = By.xpath("//div[text()=\"Reporting\"]");
    public static By reportNameScroll = By.xpath("//*[span='Select Report Name']");
    public static By suiteRunReport = By.xpath("//*[text()='Suite Run Report']");
    public static By projectScroll = By.xpath("//*[@class='p-multiselect-label p-placeholder']");
    public static By gemEcoApis = By.xpath("//*[span='GEMECOSYSTEM_APIS']");
    public static By enviromentScroll = By.xpath("//*[text()='Select Environment(s)']");
    public static By prod = By.xpath("//*[span='Prod']");
    public static By dateRangeScroll = By.xpath("//*[span='Select Date Range']");
    public static By thisYear = By.xpath("//*[@aria-label='This Year']");
    public static By seven_days = By.xpath("//li[text()=\"Last 7 days\"]");
    public static By generate = By.xpath("//*[@class='btn btn-sm stn-success themeBtn']");
    public static By copyButton = By.xpath("//*[@class='svg-inline--fa fa-copy mx-2 tabIcon']");
    public static By newTab = By.xpath("//*[@class='svg-inline--fa fa-square-arrow-up-right mx-2 tabIcon']");
    public static By createReportButton = By.xpath("//*[@class=' ms-3 btn-success btn themeBtn']");
    public static By signup = By.xpath("//*[@class='btn-text-signup fw-bold']");
    public static By firstname = By.xpath("//*[@placeholder='Firstname']");
    public static By lastname = By.xpath("//*[@placeholder='Lastname']");
    public static By username1 = By.xpath("//*[@placeholder='Username']");
    public static By emailm = By.xpath("//*[@placeholder='Email']");
    public static By password1 = By.xpath("//*[@placeholder='Password']");
    public static By confirmpass = By.xpath("//*[@placeholder='Confirm Password']");
    public static By companyname = By.xpath("//*[@placeholder='Company Name']");
    public static By register = By.xpath("//button[text()=\"Register\"]");
    public static By span = By.xpath("(//div[@class=\"text-center\"]/span)[1]");
    public static By sno = By.xpath("//*[text()='S No']");
    public static By secondPage = By.xpath("//*[@class='p-button p-component p-paginator-page p-paginator-element p-link p-highlight']");
    public static By total = By.xpath("//*[text()='Total 19 Records Found']");
    public static By total_prod = By.xpath("//*[text()='Total 15 Records Found']");
    public static By total_projects = By.xpath("//span[@class=\"p-paginator-current\"]");
    public static By request_access = By.xpath("//button[text()=\"Request Access\"]");
    public static By dropdown_of_request = By.xpath("(//div[@class=\"p-multiselect-trigger\"])[2]");
    public static By inputBox_of_request = By.xpath("//li[@class=\"p-multiselect-item\"]//span[text()=\"GEMPYP_TEST\"]");
    public static By inputBox_of_request2 = By.xpath("//li[@class=\"p-multiselect-item\"]//span[text()=\"TEST-PROJECT\"]");
    public static By select_access_request = By.xpath("(//div[@class=\"p-dropdown-trigger\"]/span)[2]");
    public static By request_access_btn = By.xpath("(//button[text()=\"Request Access\"])[2]");
    public static By admin_select = By.xpath("//li[text()=\"Admin\"]");
    public static By Alert_admin1 = By.xpath("(//div[contains(@class,'Toastify__toast-body')]//div)[2]");
    public static By Alert_admin2=By.xpath("//div[contains(@class,'Toastify__toast-container--top-right')]//child::div[contains(@class,'Toastify__toast-body')]/div[2]");
    public static By email_already_existss=By.xpath("//div[contains(@class,'Toastify__toast-container Toastify__toast-container--top-left')]//child::div[contains(@class,'Toastify__toast-body')]/div[2]");
    public static By project_deleting=By.xpath("//td[@class=\"align-middle\"]/div[@class=\"typewriter\"]");
    public static By create_project=By.xpath("//button[text()=\"Create Project\"]");
    public static By project_name_create_project = By.xpath("//input[@placeholder=\"Project Name\"]");
    public static By enviro_create_project = By.xpath("//li[@class=\"p-chips-input-token\"]//input");
    public static By textArea = By.xpath("//textarea[@id=\"desc\"]");
    public static By create_button_Admin=By.xpath("//button[text()=\"Create\"]");
    public static By project_name_Admin=By.xpath("(//td/div[@class=\"text-left\"]/span)[1]");
    public static By desc_name_admin=By.xpath("(//td/div[@class=\"text-left\"]/span)[2]");
    public static By delete_no_btn=By.xpath("//div[@class=\"btn btn-danger mx-2\"]");
    public static By delete_yes_btn=By.xpath("//div[@class=\"btn btn-success\"]");
    public static By save_admin_button=By.xpath("//button[text()=\"Save\"]");
    public static By project_desc_Admin=By.xpath("(//td/div[@class=\"text-left\"]/span)[2]");
    public static By crossCreateReport = By.xpath("//*[@class='p-dialog-header-icon p-dialog-header-close p-link']");
    public static By pass = By.xpath("//span[text()='Beta']//ancestor::td//following-sibling::td//div[text()='FAIL']");
    public static By prod_suiteRunRpt = By.xpath("//div[text()=\"PASS\"]");
    public static By filter = By.xpath("(//button[@class='p-column-filter-menu-button p-link'])[4]//span");
    public static By selectFilter = By.xpath("//*[text()='Select Option(s)']");
    public static By selectFilter100 = By.xpath("//*[text()='1 items selected']");
    public static By selectPass = By.xpath("//div[text()='FAIL']//ancestor::span//preceding-sibling::div/div");
    public static By selectPass_prod = By.xpath("//div[text()='PASS']//ancestor::span//preceding-sibling::div/div");
    public static By closeFilter = By.xpath("//*[@class='p-multiselect-close p-link']//span");
    public static By selct_pass_text = By.xpath("//div[@class='p-multiselect-representative-option']//div[text()='FAIL']");
    public static By selct_pass_text_prod = By.xpath("//span[@class=\"image-text\"]//div[text()='PASS']");
    public static By selectFilter1 = By.xpath("//*[text()='1 items selected']");
    public static By exe = By.xpath("//div[text()='INFO']//ancestor::span//preceding-sibling::div/div");
    public static By select_exe_text = By.xpath("//span[@class='image-text']/div[text()='EXE']");
    public static By exe1 = By.xpath("//div[@class='btn btn-sm statusBtn btn-success exe-btn']");
    public static By fail = By.xpath("//div[text()='FAIL']//ancestor::span//preceding-sibling::div/div");
    public static By select_fail_text = By.xpath("//span[@class=\"image-text\"]//div[text()='FAIL']");
    public static By fail1 = By.xpath("//div[@class='btn btn-sm statusBtn btn-success fail-btn ']");
    public static By warn = By.xpath("//div[text()='PASS']//ancestor::span//preceding-sibling::div/div");
    public static By select_warn_text = By.xpath("//span[@class='image-text']/div[text()='WARN']");
    public static By warn1 = By.xpath("//div[@class='btn btn-sm statusBtn btn-success warn-btn']");
    public static By filter1 = By.xpath("(//button[@class='p-column-filter-menu-button p-link'])[7]//span");
    public static By selectDate = By.xpath("(//div[@class='p-multiselect-representative-option'])[3]//span");
    public static By select_date_text = By.xpath("(//div[@class='text-center'])[4]");
    public static By action = By.xpath("(//div[@class='actionBtn'])[1]");
    public static By executionR = By.xpath("//*[text()='Execution Report']");
    public static By newtb_button = By.xpath("(//*[@class='svg-inline--fa fa-square-arrow-up-right mx-2 tabIcon'])[2]");
    public static By testcaseDetail = By.xpath("//*[text()='Testcase Details']");
    public static By keyofJson = By.xpath("//pre[contains(text(),'data')]");
    public static By alert_functionality=By.xpath("//a[text()=\"Widgets\"]");
    public static By see_more = By.xpath("(//span[text()=\"See More\"])[1]");
    public static By click_here = By.xpath("//a[text()=\"Click here\"]");
    public static By company_new_name=By.xpath("(//tr/td/div/span/span[@class=\" \"])[2]");
    public static By companyCountSuper=By.xpath("(//tr/td/div/span/span[@class=\" \"])[1]");
    public static By nextPageSuperAdmin=By.xpath("//button[@aria-label=\"Next Page\"]");
    public static By nextPageSuperAdmin2=By.xpath("//button[@aria-label=\"Previous Page\"]");
    public static By lastPageSuperAdmin2=By.xpath("//button[@aria-label=\"First Page\"]");
    public static By lastPageSuperAdmin=By.xpath("//button[@aria-label=\"Last Page\"]");
    public static By company_Count=By.xpath("//span[@class=\"p-paginator-current\"]");
    public static By verify_confirmation=By.xpath("(//span[@class=\"pass-color boldText \"])[1]");
    public static By unverify_confirmation=By.xpath("(//span[@class=\" fail-color boldText\"])[1]");
    public static By browser_isCompat = By.xpath("//strong[text()=\"If File is Browser Compatible it will open in new Window else it will download the file.\"]");
    public static By demo_test = By.xpath("(//div[@class=\"text-left\"])[1]");
    public static By selectFilter3 = By.xpath("(//*[@class='p-column-filter-menu-button p-link'])[11]");
    public static By select_filter = By.xpath("(//*[@class='p-multiselect-trigger'])");
    public static By click_filter = By.xpath("(//*[@class='p-checkbox-box'])[2]");
    public static By close_filter = By.xpath("(//*[@class='p-multiselect-close-icon pi pi-times'])");
    public static By close_filter1 = By.xpath("(//*[@class='btn btn-sm statusBtn btn-success pass-btn'])[9]");
    public static By inside_filter_text = By.xpath("(//*[text()='August 16, 2022 5:20:03 PM (IST)'])[3]");
    public static By outside_filter_text = By.xpath("(//*[text()='August 16, 2022 5:20:03 PM (IST)'])[1]");
    public static By login_screen = By.xpath("//span[text()='Log in']");
    public static By scroll_down = By.xpath("(//*[@class=\"p-dropdown-trigger\"])[2]");
    public static By select_24 = By.xpath("(//*[@class=\"p-dropdown-item\"])[1]");
    public static By suite_detail = By.xpath("(//*[text()=\"suite details are not found\"])");
    public static By all_f = By.xpath("(//*[text()=\"All fields are required !\"])");
    public static By cross_b = By.xpath("//*[@class=\"cross btn-sm ms-auto d-flex align-items-center\"]");
    public static By open_n = By.xpath("//*[text()=\"Open New Tab\"]");
    public static By suite_sum = By.xpath("//*[text()=\"Suite Summary Report\"]");
    public static By suite_sum_text = By.xpath("//*[text()=\"Suite Summary Report\"]");
    public static By select_all = By.xpath("(//*[@class=\"p-checkbox-box\"])[1]");
    public static By select_all2 = By.xpath("(//*[@class=\"p-checkbox-box\"])[1]");
    public static By pie_filter = By.xpath("(//*[@class=\"p-column-filter-menu-button p-link\"])[4]");
    public static By pie_filter_prod = By.xpath("(//span[@class=\"pi pi-filter-icon pi-filter\"])[4]");
    public static By select_pie = By.xpath("(//*[@class=\"p-multiselect-trigger\"])");
    public static By select_pie2 = By.xpath("(//*[@class=\"p-checkbox-box\"])[2]");
    public static By pie1 = By.xpath("//div[@class=\"text-center mb-3 fontSizeGeneral\"]/strong");
    public static By pie2 = By.xpath("(//div[@class=\"text-center mb-3 fontSizeGeneral\"])[2]/strong");
    public static By close_pie = By.xpath("(//*[@class=\"p-multiselect-close p-link\"])");
    public static By close_pie2 = By.xpath("(//*[@class=\"image-text\"])[1]");
    public static By no_select = By.xpath("(//*[@class=\"p-checkbox-icon p-c pi pi-check\"])");
    public static By pie_countt = By.xpath("//canvas");
    public static By total_text = By.xpath("(//*[@class=\"p-paginator-current\"])");
    public static By edit_report_btn = By.xpath("//*[text()=\"Edit Report\"]");
    public static By suite_rpt_clck = By.xpath("//*[span='Suite Summary Report']");
    public static By sun_rn_rpt_txt = By.xpath("//*[text()=\"Suite Run Report\"]");
    public static By envrmnt_fltrr = By.xpath("(//*[@class=\"p-column-filter-menu-button p-link\"])[3]");
    public static By enviromnt_filter_prod = By.xpath("(//*[@class=\"p-column-filter-menu-button p-link\"])[3]");
    public static By betaa = By.xpath("(//*[@class=\"p-checkbox-box\"])[2]");
    public static By beta_txt = By.xpath("//span[@class=\"image-text\"]/span[text()=\"Prod\"]");
    public static By prod_txt = By.xpath("//span[@class=\"image-text\"]/span[text()=\"Prod\"]");
    public static By betas = By.xpath("(//*[text()=\"Prod\"])");
    public static By prods = By.xpath("(//*[text()=\"Prod\"])");
    public static By betaa2 = By.xpath("(//*[@class=\"p-checkbox-icon p-c pi pi-check\"])");
    public static By shared_reportt = By.xpath("//*[text()=\"Shared Report\"]");
    public static By shared_pie = By.xpath("//*[@class=\"p-column-filter-menu-button p-link p-column-filter-menu-button-active\"]");
    public static By suite_diag = By.xpath("//*[text()=\"Suite Diagnose Report\"]");
    public static By testcase_diag = By.xpath("//*[text()=\"Testcase Diagnose Report\"]");
    public static By testcase_run_rpt = By.xpath("//*[text()=\"Testcase Run Report \"]");
    public static By testcase_summ_rpt = By.xpath("//*[text()=\"Testcase Summary Report\"]");
    public static By last_run_status = By.xpath("(//*[@class=\"p-column-filter-menu-button p-link\"])[4]");
    public static By last_run_status_prod = By.xpath("(//button[@class=\"p-column-filter-menu-button p-link\"])[4]");
    public static By suite_run_filter = By.xpath("(//*[@class=\"p-column-filter-menu-button p-link\"])[4]");
    public static By suite_run_filter_prod = By.xpath("(//button[@class=\"p-column-filter-menu-button p-link\"])[4]");
    public static By select_daily_beta_reg = By.xpath("(//*[@class=\"p-checkbox-box\"])[2]");
    public static By daily_beta_reg_text = By.xpath("(//div[@class=\"p-multiselect-representative-option\"])[1]");
    public static By daily_betas_reg_text = By.xpath("(//span[text()=\"PYPREST REGRESSION\"])");
    public static By daily_betas_reg_text_prod = By.xpath("(//span[text()=\"TEST_REGRESSION\"])");
    public static By project_name_fltr = By.xpath("(//*[@class=\"p-column-filter-menu-button p-link\"])[1]");
    public static By pygem_project_select = By.xpath("(//*[@class=\"p-checkbox-box\"])[2]");
    public static By pygem_project_txt = By.xpath("//div[@class=\"text-left\"]//span[text()=\"Gemecosystem_apis\"]");
    public static By pygem_project_txts = By.xpath("(//*[text()=\"pygem_project\"])");
    public static By broken_index_filtr = By.xpath("(//*[@class=\"p-column-filter-menu-button p-link\"])[4]");

    public static By reloadJAR = By.xpath("//button[text()=\"Reload JAR\"]");

    public static By reloadJAR_txt = By.xpath("//div[text()=\"jar file creation started successfully \"]");
    public static By broken_index_filtr_prod = By.xpath("(//button[@class=\"p-column-filter-menu-button p-link\"])[4]");
    public static By broken_index_slct = By.xpath("(//*[@class=\"p-checkbox-box\"])[2]");
    public static By broken_index_txt = By.xpath("(//span[text()=\"0\"])[2]");
    public static By broken_index_txts = By.xpath("(//span[text()=\"0\"])");
    public static By broken_index_prod = By.xpath("(//span[text()=\"0\"])");
    public static By test_case_run_rpt_txt = By.xpath("//div[text()=\"Testcase Run Report \"]");
    public static By testTool = By.xpath("//div[text()=\"Test Tool\"]");
    public static By suite = By.xpath("//div[text()=\"Suite\"]");
    public static By testCasePlus = By.xpath("(//*[local-name()='svg' and @data-icon='square-plus']/*[local-name()='path'])[1]");
    public static By tick_option=By.xpath("(//*[local-name()='svg' and @data-icon=\"circle-check\"]/*[local-name()='path'])[1]");
    public static By unlink_option=By.xpath("(//*[local-name()='svg' and @data-icon=\"ban\"]/*[local-name()='path'])[1]");
    public static By testCasePlus2 = By.xpath("(//*[local-name()='svg' and @data-icon='square-plus']/*[local-name()='path'])[4]");
    public static By testCasePlus3 = By.xpath("(//*[local-name()='svg' and @data-icon='square-plus']/*[local-name()='path'])[2]");
    public static By testcase = By.xpath("//div[text()=\"Testcases\"]");
    public static By getTestcaseCount = By.xpath("(//div[@class=\"text-left\"]//span)[7]");
    public static By import_from_lib = By.xpath("//div[text()=\"Import from Library\"]");
    public static By checkbox1 = By.xpath("(//div[@aria-label=\"Select null\"])[1]");
    public static By checkbox2 = By.xpath("(//div[@aria-label=\"Select null\"])[2]");
    public static By checkbox3 = By.xpath("(//div[@aria-label=\"Select null\"])[3]");
    public static By unselectCheckbox = By.xpath("(//div[@aria-label=\"Unselect null\"])");
    public static By importButton = By.xpath("//button[text()=\"Import\"]");
    public static By createTestcasess = By.xpath("//div[text()=\"Create Testcase\"]");
    public static By testcaseNamess = By.xpath("//input[@placeholder=\"Testcase Name\"]");
    public static By categoryNamess = By.xpath("//input[@placeholder=\"Category\"]");
    public static By firsttestcaseName = By.xpath("(//div[@class=\"text-left\"]/span/span[contains(text(),'TESTER_0.')])[1]");
    public static By pencil = By.xpath("(//*[local-name()='svg' and @data-icon=\"pencil\"]/*[local-name()='path'])[1]");
    public static By beforeTestCaseName = By.xpath("((//tbody)[2]/tr/td/div/span/span)[2]");
    public static By beforeCategoryName = By.xpath("((//tbody)[2]/tr/td/div/span/span)[3]");
    public static By typeName = By.xpath("((//tbody)[2]/tr/td/div/span/span)[4]");
    public static By saveOption = By.xpath("//button[@class=\"btn-success mt-3  btn themeBtn\"]");
    public static By categorys = By.xpath("//input[@placeholder=\"Category\"]");
    public static By typess = By.xpath("//div[@aria-label=\"Select Type\"]");
    public static By selectKeys = By.xpath("//div[@aria-label=\"Select Key\"]");
    public static By api_slct = By.xpath("//li[text()=\"api\"]");
    public static By testcaseIDd = By.xpath("//span[text()=\"Testcase ID\"]");
    public static By typeSelect = By.xpath("//li[text()=\"PYPREST\"]");
    public static By createTestcaseButton = By.xpath("//button[text()=\"Create Testcase\"]");
    public static By getTestcaseCountAlter = By.xpath("(//div[@class=\"text-center\"]//span)[1]");
    public static By create_testcase_button = By.xpath("//div[text()=\"Create Testcase\"]");
    public static By importFromLib = By.xpath("//div[text()=\"Import from Library\"]");
    public static By create_suite_button = By.xpath("//div[text()=\"Create Suite\"]");
    public static By upload_button = By.xpath("//div[text()=\"Upload\"]");
    public static By globalCross = By.xpath("//span[@class=\"p-dialog-header-close-icon pi pi-times\"]");

    public static By fileUpload = By.xpath("//input[@class=\"mx-1\"]");
    public static By browseBtn = By.xpath("//div[text()=\"Browse\"]");
    public static By tescaseSize = By.xpath("//td[@class=\"columnsPrime\"]");
    public static By suite_ID = By.xpath("(//div[@class=\"text-left\"]//span)[1]");
    public static By new_suiteIDs = By.xpath("(//div[@class=\"text-left\"]//span)[32]");
    public static By suite_name = By.xpath("(//div[@class=\"text-left\"]//span)[3]");
    public static By new_suiteName = By.xpath("(//div[@class=\"text-left\"]//span)[34]");
    public static By textName = By.xpath("//*[@class=\"p-datatable-header\"]");
    public static By suiteIDList = By.xpath("//tr/td[1]//span/span");
    public static By testcaseIDList = By.xpath("//span[text()='Testcase ID']//ancestor::table//tr/td[2]//span/span");
    public static By binOption = By.xpath("(//*[local-name()='svg' and @data-icon=\"trash\"]/*[local-name()='path'])[1]");
    public static By testcase_COUNT = By.xpath("(//div[@class=\"text-center\"]//span)[1]");
    public static By zeroTestCase = By.xpath("//div[text()=\"0 Testcase(s) Found. Create/Add new Testcase(s) to execute Suite.\"]");
    public static By getTheStatus = By.xpath("(//div[@class=\"text-center\"]/div)[1]");
    public static By elementDivtext = By.xpath("//div[@class=\"dialogExecuteSuite\"]");
    public static By wait_for_fail = By.xpath("//table//div[@class='columnsPrime   ']");
    public static By yesOPtion = By.xpath("//div[@class=\"btn btn-success\"]");
    public static By noOption = By.xpath("//div[@class=\"btn btn-danger mx-2\"]");
    public static By linkClick = By.xpath("//div[@class=\"container text-center  mt-3\"]/a");
    public static By hasNext2 = By.xpath("//button[text()=\"1\"]");
    public static By hasNext3 = By.xpath("//button[text()=\"3\"]");
    public static By hasNext4 = By.xpath("//button[text()=\"4\"]");
    public static By buttons = By.xpath("//span[@class=\"p-paginator-pages\"]/button");
    public static By super_admin=By.xpath("//div[text()=\"Super Admin\"]");
    public static By select_company_name=By.xpath("//input[@placeholder=\"Select Company Name\"]");
    public static By nextPageBtn = By.xpath("//button[@aria-label='Next Page']");
    public static By nextPageBtn2 = By.xpath("(//button[@aria-label='Next Page'])[2]");
    public static By testcaseUpdated = By.xpath("//div[text()=\"Testcase updated successfully !\"]");
    public static By jarFilter = By.xpath("(//span[@class=\"pi pi-filter-icon pi-filter\"])[4]");
    public static By jarSelect = By.xpath("//span[text()=\"GEMJAR\"]");
    public static By GIT = By.xpath("(//*[local-name()='svg' and @data-icon=\"github\"]/*[local-name()='path'])[1]");
    public static By GIT2 = By.xpath("(//*[local-name()='svg' and @data-icon=\"github\"]/*[local-name()='path'])[2]");
    public static By GIT3 = By.xpath("(//*[local-name()='svg' and @data-icon=\"github\"]/*[local-name()='path'])[3]");
    public static By GIT4 = By.xpath("(//*[local-name()='svg' and @data-icon=\"github\"]/*[local-name()='path'])[4]");
    public static By Execution_btn = By.xpath("(//*[local-name()='svg' and @data-icon=\"arrow-up-right-from-square\"]/*[local-name()='path'])[1]");
    public static By testcase_plus_opt = By.xpath("(//*[local-name()='svg' and @data-icon=\"circle-plus\"]/*[local-name()='path'])[1]");
    public static By ss_click = By.xpath("(//img[@class=\"thumbnail \"])[1]");
    public static By open_full_screen = By.xpath("//button/span[@class=\"p-dialog-header-maximize-icon pi pi-window-maximize\"]");
    public static By close_button_ss = By.xpath("//button[@aria-label=\"Close\"]");
    public static By allFiel = By.xpath("//div[text()=\"All fields are required !\"]");
    public static By repoIsPvt = By.xpath("//input[@type=\"checkbox\"]");
    public static By GITlink = By.xpath("//input[@placeholder=\"Git Link\"]");
    public static By accessToken = By.xpath("//input[@placeholder=\"Personal Access Token\"]");
    public static By integrateGIT = By.xpath("//button[text()=\"Integrate Git\"]");
    public static By testcaseDeleted = By.xpath("//div[text()=\"Testcase Deleted Successfully.\"]");
    public static By editTestcaseCross = By.xpath("//div[@class=\"text-center col-md-1 col-sm-1\"]");
    public static By testcaseNotCreated = By.xpath("//div[text()=\"Testcase Name, Category and Type Cannot be Empty\"]");
    public static By playicon = By.xpath("(//*[local-name()='svg' and @data-icon='circle-play']/*[local-name()='path'])[1]");
    public static By playicon2 = By.xpath("(//*[local-name()='svg' and @data-icon='circle-play']/*[local-name()='path'])[3]");
    public static By playiconCross = By.xpath("//span[@class=\"p-dialog-header-close-icon pi pi-times\"]");
    public static By addDataButton = By.xpath("//button[text()=\"Add Data\"]");
    public static By modeScroll = By.xpath("(//div[@class=\"p-dropdown-trigger\"])[2]");
    public static By modeScroll2 = By.xpath("(//div[@class=\"p-dropdown-trigger\"])[3]");
    public static By clickAnywhere = By.xpath("//div[text()=\"Edit Testcase\"]");
    public static By dvSelect = By.xpath("//li[text()=\"DV\"]");
    public static By modeSelect = By.xpath("//li[text()=\"Sequence\"]");
    public static By modeSelect2 = By.xpath("//li[text()=\"Optimize\"]");
    public static By envScroll = By.xpath("(//div[@class=\"p-dropdown-trigger\"])[3]");
    public static By envScroll2 = By.xpath("(//div[@class=\"p-dropdown-trigger\"])[4]");
    public static By envSelect = By.xpath("//li[text()=\"Beta\"]");
    public static By url = By.xpath("(//div[@class=\"p-dropdown-trigger\"])[4]");
    public static By url2 = By.xpath("(//div[@class=\"p-dropdown-trigger\"])[5]");
    public static By addDataOpt = By.xpath("(//div[@class=\"p-dropdown-trigger\"])[5]");
    public static By addDataOpt2 = By.xpath("(//div[@class=\"p-dropdown-trigger\"])[6]");
    public static By selectKey = By.xpath("(//span[text()=\"Select Key\"])");
    public static By thread_count = By.xpath("//li[text()=\"thread-count\"]");
    public static By hundered = By.xpath("//b[contains(text(),\"100\")]");
    public static By dbConfigPath = By.xpath("//li[text()=\"db_config_path\"]");
    public static By addDataInput = By.xpath("(//input[@placeholder=\"Value\"])[2]");
    public static By urlSelect = By.xpath("//li[text()=\"base_url\"]");
    public static By valueInput = By.xpath("(//input[@placeholder=\"Value\"])[1]");
    public static By valueInpt = By.xpath("(//input[@placeholder=\"Value\"])[2]");
    public static By testcaseToBeDel = By.xpath("((//tbody)[2]/tr/td/div/span/span)[1]");
    public static By listTestcaseDetail = By.xpath("//tr[@class=\"testcaseTablerow\"]/td");
    public static By rightArrow = By.xpath("//span[@class=\"p-row-toggler-icon pi pi-arrow-circle-right\"]");
    public static By addDataCross = By.xpath("(//div[@class=\"text-center col-md-1 col-sm-1\"])[2]");
    public static By executeButton = By.xpath("//button[text()=\"Execute\"]");
    public static By select_gempyp = By.xpath("(//span[text()=\"Select\"])[1]");
    public static By back_gem_opt = By.xpath("(//span[text()=\"Back\"])[1]");
    public static By select_pr_name = By.xpath("(//div[@class=\"p-dropdown-trigger\"])[2]");
    public static By GEMeCO_api = By.xpath("(//li[text()=\"GEMECO-API-PY\"])[1]");
    public static By removeGIT = By.xpath("//button[text()=\"Remove Git\"]");
    public static By gitUnlink = By.xpath("//div[text()=\"Git Unlinked from Suite Id: 933 \"]");
    public static By updateGIT = By.xpath("//div[text()=\"Testcase(s) updated successfully \"]");
    public static By updateGITBtn = By.xpath("//button[text()=\"Update/Reload Git\"]");
    public static By input_suite_nm = By.xpath("//input[@placeholder=\"Suite Name\"]");
    public static By create_suite = By.xpath("//button[text()=\"Create Suite\"]");
    public static By gemjar_select = By.xpath("(//span[text()=\"Select\"])[2]");
    public static By allFields = By.xpath("//div[text()=\"Suite with this name exists for this project\"]");

    public static By suite_created = By.xpath("//div[text()=\"Suite Created Successfully !\"]");
    public static By new_uniq = By.xpath("(//div[@class=\"text-left\"]/span)[2]");
    public static By total_COunt = By.xpath("//span[@class=\"p-paginator-current\"]");
    public static By getTotal_COunt2 = By.xpath("(//span[@class=\"p-paginator-current\"])[2]");
    public static By suite_id_btn = By.xpath("//span[text()=\"Suite ID\"]");
    public static By select_Zero = By.xpath("(//div[@class=\"p-checkbox p-component\"])[2]");
    public static By zeroText = By.xpath("//span[@class=\"image-text\"]/span[text()=\"0\"]");
    public static By zero_list = By.xpath("//tr/td[5]//span/span");
    public static By filterBroken = By.xpath("(//span[@class=\"pi pi-filter-icon pi-filter\"])[5]");
    public static By testcaseID = By.xpath("(//span[@class=\"pi pi-filter-icon pi-filter\"])[10]");
    public static By noTestCase = By.xpath("//strong[contains(text(),'No Testcase(s) Found')]");
    public static By createTestcase = By.xpath("//td/center");
    public static By testCaseIdText = By.xpath("(//div[@class=\"p-multiselect-representative-option\"])[1]");
    public static By testCaseIdTexts = By.xpath("//td[@class=\"columnsPrime  maxWidthTableText \"][1]");
    public static By admin = By.xpath("//div[text()=\"Admin\"]");
    public static By edit_project_details = By.xpath("(//*[local-name()='svg' and @data-icon='pen-to-square' and contains(@class,'disabledIcon')]/*[local-name()='path'])[1]");
    public static By edit_project_details2 = By.xpath("(//*[local-name()='svg' and @data-icon='pen-to-square' and not(contains(@class,'disabledIcon'))]/*[local-name()='path'])[1]");
  //  public static By edit_project_details3=By.xpath("(//div/*[local-name()='svg' and @data-icon='pen-to-square']/*[local-name()='path'])[1]");
    public static By delete_project = By.xpath("(//*[local-name()='svg' and @data-icon=\"trash-can\" and contains(@class,\"disabledIcon\")]/*[local-name()='path'])[1]");
    public static By delete_project2 = By.xpath("(//*[local-name()='svg' and @data-icon=\"trash-can\" and not(contains(@class,\"disabledIcon\"))]/*[local-name()='path'])[1]");
    public static By edit_access = By.xpath("(//*[local-name()='svg' and @data-icon=\"circle-user\" and contains(@class,\"disabledIcon\")]/*[local-name()='path'])[1]");
    public static By edit_access2 = By.xpath("(//*[local-name()='svg' and @data-icon=\"circle-user\" and not(contains(@class,\"disabledIcon\"))]/*[local-name()='path'])[1]");
    public static By addUser_project=By.xpath("//div[@class='nav-link addUserLink']");
    public static By changerole_tab=By.xpath("//div[@class='nav-link changeRoleLink']");
    public static By users_list=By.xpath("//div[@id='pills-tabContent']//tr/td[2]");
    public static By adduser_select=By.xpath("//div[@id='pills-tabContent']//div[@class='p-multiselect-label-container']/div[contains(@class,'p-multiselect-label')]");
    public static By addUser_search=By.xpath("//input[@class='p-inputtext p-component p-multiselect-filter']");
    public static By add_user=By.xpath("//li/div[@class='p-checkbox p-component']");
    public static By select_role_empty=By.xpath("//span[text()='Select Access Role(s)']");
    public static By select_role=By.xpath("//li[@aria-label='Admin']");
    public static By adduser_btn=By.xpath("//button[text()='Add User']");
    public static By delete_user2=By.xpath("(//div[@id='pills-changeRole']//*[local-name()='svg' and @data-icon=\"trash-can\"]/*[local-name()='path'])[2]");
}

